name: Publish

# Inspired by: 
# https://dev.to/xcanchal/automatic-versioning-in-a-lerna-monorepo-using-github-actions-4hij

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Use NodeJS 18"
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: yarn install
      
    - name: Run build
      run: yarn build

    - name: Run test
      run: yarn test

    - name: Run lint
      run: yarn lint
    
    - name: "Version and publish"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Set git user"
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        echo "Version"
        yarn dlx lerna version \
          --conventional-commits \
          --yes
        
        echo "Publish"
        yarn dlx lerna publish from-git \
          --loglevel debug \
          --yes