name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Use NodeJS 18"
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run build
      run: yarn test

    - name: "Setup yarn"
      run: |
          yarn config set -H 'npmAuthToken' "${{secrets.GITHUB_TOKEN}}"
      
    - name: "Version and publish"
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        npx lerna version \
          --conventional-commits \
          --conventional-graduate \
          --yes

        npx lerna publish from-git \
          --yes